codeworld:
  jwt:
    secret: codeworld@Login(Auth}*^31)&codeworld% # 用于生存rsa公钥和私钥的密文,越复杂越好
    pubKeyPath: \xiangmu\demo\codeworld-cloud-shop-master\rsa.pub # 公钥地址
    priKeyPath: \xiangmu\demo\codeworld-cloud-shop-master\rsa.pri # 私钥地址
    expire: 30   # 过期时间,单位分钟
    cookieMaxAge: 1800
    cookieName: token
  worker:
    workerId: 1
    datacenterId: 1
  order:
    excel:
      title: 序号,订单编号,订单提交时间,订单支付时间,订单发货时间,订单结束时间,订单关闭时间,会员名称,订单金额(元),订单实付金额(元),订单状态,物流公司,物流单号
logging:
  config: classpath:log/logback-spring.xml
  level:
    com.codeworld.fc.order.mapper: debug

feign:
  httpclient:
    enabled: false
    connection-timeout: 3000
  okhttp:
    enabled: true
  hystrix:
    enabled: false