mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
actable:
  table:
    auto: update
  model:
    pack: com.codeworld.fc.*.entity
  database:
    type: mysql