server:
  port: 9001
spring:
  application:
    name: codeworld-cloud-goods
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      - config
    include:
      - config
      - db
      - mybatis
      - nacos
      - rabbitmq
      - redis
      - xxl