codeworld:
  jwt:
    secret: codeworld@Login(Auth}*^31)&codeworld% # 用于生存rsa公钥和私钥的密文,越复杂越好
    pubKeyPath: \xiangmu\demo\codeworld-cloud-shop-master\rsa.pub # 公钥地址
    priKeyPath: \xiangmu\demo\codeworld-cloud-shop-master\rsa.pri # 私钥地址
    expire: 30   # 过期时间,单位分钟
    cookieMaxAge: 1800
    cookieName: token
logging:
  config: classpath:log/logback-spring.xml
  level:
    com.codeworld.fc.order.mapper: debug