server:
  port: 5002
spring:
  application:
    name: codeworld-cloud-merchant
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      - config
    include:
      - admin
      - config
      - db
      - mybatis
      - nacos
      - redis
      - xxl
