server:
  port: 8004
spring:
  application:
    name: codeworld-cloud-auth
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
#      - config
    include:
      - admin
      - config
      - nacos

